<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dated_news"
 *
 * Auto generated by Extension Builder 2017-01-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dated News',
	'description' => 'Extends the TYPO3 versatile news system extension tx_news with a calendar view using fullcalendar.js/qtip.js and allows to book for the now pricable events',
	'category' => 'fe',
	'author' => 'Falk Röder',
	'author_email' => 'mail@falk-roeder.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '4.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.3.99',
			'news' => '5.0.0-5.3.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);