<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dated_news"
 *
 * Auto generated by Extension Builder 2015-07-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dated News',
	'description' => 'Extends the TYPO3 versatile news system extension tx_news with a calendar view',
	'category' => 'fe',
	'author' => 'Falk Röder',
	'author_email' => 'mail@falk-roeder.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.10-7.99.99',
			'news' => '3.2.2'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);