<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_calendar"
 *
 * Auto generated by Extension Builder 2015-07-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'newscalendar',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Falk Röder',
	'author_email' => 'mail@falk-roeder.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.00',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'news' => '3.2'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);